/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export const DotsMealsDalEnumsDietType = {
  None: 0,
  Vegetarian: 1,
  Vegan: 2,
  Pescatarian: 3,
  Keto: 4,
  LowCarb: 5,
  OvoVegetarian: 6,
  LactoVegetarian: 7,
  LactoOvoVegetarian: 8,
  WholeFoodPlantBased: 9,
  GlutenFree: 10,
  DairyFree: 11,
  Halal: 12,
  Kosher: 13
}

export type DotsMealsDalEnumsDietType = typeof DotsMealsDalEnumsDietType[keyof typeof DotsMealsDalEnumsDietType]
