/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export const DotsMealsDalEnumsActivityLevels = {
  SEDENTARY: 1,
  LIGHTLY_ACTIVE: 2,
  MODERATELY_ACTIVE: 3,
  VERY_ACTIVE: 4,
  SUPER_ACTIVE: 5
}

export type DotsMealsDalEnumsActivityLevels = typeof DotsMealsDalEnumsActivityLevels[keyof typeof DotsMealsDalEnumsActivityLevels]
