/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export const DotsMealsDalEnumsGenders = {
  MALE: 1,
  FEMALE: 2
}

export type DotsMealsDalEnumsGenders = typeof DotsMealsDalEnumsGenders[keyof typeof DotsMealsDalEnumsGenders]
