/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EnumsRetrieveTranslationsEnumOption {
  Description?: string;
  Key?: string;
  Value?: number;
}
