/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EnumsRetrieveTranslationsEnumOption } from '../models/enums-retrieve-translations-enum-option';
export interface EnumsRetrieveTranslationsEnumOptions {
  EnumName?: string;
  Options?: Array<EnumsRetrieveTranslationsEnumOption>;
}
