/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DotsMealsDalEnumsActivityLevels } from '../models/dots-meals-dal-enums-activity-levels';
import { DotsMealsDalEnumsDietType } from '../models/dots-meals-dal-enums-diet-type';
import { DotsMealsDalEnumsGenders } from '../models/dots-meals-dal-enums-genders';
export interface UserRetrieveLoggedUserResponse {
  ActivityLevel?: DotsMealsDalEnumsActivityLevels | null;
  Allergies?: string | null;
  BirthDate?: string;
  DietType?: DotsMealsDalEnumsDietType | null;
  Gender?: DotsMealsDalEnumsGenders;
  Goal?: string | null;
  Height?: number;
  Name?: string;
  Weight?: number;
}
