/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserRetrieveLoggedUserResponse {
  BirthDate?: string
  Height?: number
  Name?: string
  Weight?: number
}
