services:
  dots.meals.api:
    image: ghcr.io/giorgiodots/dots-meals:prod
    container_name: dotsmealsapi
    build:
      context: .
      dockerfile: Dots.Meals.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    secrets:
      - db_url
      - jwt_secret
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - DB_URL_FILE=/run/secrets/db_url
      - JWT_SECRET_FILE=/run/secrets/jwt_secret
      - JWT_ISSUER=http://auth.giorgio-dots.com
      - JWT_AUDIENCE=dots-meals-4f8a2c7b-9d3f-4a6e-bc1a-72e8a5d01234
      - ALLOWED_ORIGINS=http://localhost:4200

secrets:
  db_url:
    file: ./secrets/db_url.secret
  jwt_secret:
    file: ./secrets/jwt_secret.secret