/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { RequestBuilder } from '../../request-builder'

import { DotsMealsApiFeaturesUserRetrieveLoggedUserResponse } from '../../models/dots-meals-api-features-user-retrieve-logged-user-response'

export interface DotsMealsApiFeaturesUserRetrieveLoggedUserEndpoint$Params {}

export function dotsMealsApiFeaturesUserRetrieveLoggedUserEndpoint(
  http: HttpClient,
  rootUrl: string,
  params?: DotsMealsApiFeaturesUserRetrieveLoggedUserEndpoint$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<DotsMealsApiFeaturesUserRetrieveLoggedUserResponse>> {
  const rb = new RequestBuilder(
    rootUrl,
    dotsMealsApiFeaturesUserRetrieveLoggedUserEndpoint.PATH,
    'post',
  )
  if (params) {
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DotsMealsApiFeaturesUserRetrieveLoggedUserResponse>
    }),
  )
}

dotsMealsApiFeaturesUserRetrieveLoggedUserEndpoint.PATH = '/api/user/retrieve-logged-user'
