/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { enumsRetrieveTranslationsEndpoint } from '../fn/enums-features/enums-retrieve-translations-endpoint';
import { EnumsRetrieveTranslationsEndpoint$Params } from '../fn/enums-features/enums-retrieve-translations-endpoint';
import { EnumsRetrieveTranslationsEnumOptions } from '../models/enums-retrieve-translations-enum-options';

@Injectable({ providedIn: 'root' })
export class EnumsFeaturesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `enumsRetrieveTranslationsEndpoint()` */
  static readonly EnumsRetrieveTranslationsEndpointPath = '/enums-features/retrieve-translations';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `enumsRetrieveTranslationsEndpoint()` instead.
   *
   * This method doesn't expect any request body.
   */
  enumsRetrieveTranslationsEndpoint$Response(params?: EnumsRetrieveTranslationsEndpoint$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EnumsRetrieveTranslationsEnumOptions>>> {
    return enumsRetrieveTranslationsEndpoint(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `enumsRetrieveTranslationsEndpoint$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  enumsRetrieveTranslationsEndpoint(params?: EnumsRetrieveTranslationsEndpoint$Params, context?: HttpContext): Observable<Array<EnumsRetrieveTranslationsEnumOptions>> {
    return this.enumsRetrieveTranslationsEndpoint$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<EnumsRetrieveTranslationsEnumOptions>>): Array<EnumsRetrieveTranslationsEnumOptions> => r.body)
    );
  }

}
