/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { mealsGeneratePlanEndpoint } from '../fn/meals-features/meals-generate-plan-endpoint';
import { MealsGeneratePlanEndpoint$Params } from '../fn/meals-features/meals-generate-plan-endpoint';
import { MealsGeneratePlanResponse } from '../models/meals-generate-plan-response';

@Injectable({ providedIn: 'root' })
export class MealsFeaturesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `mealsGeneratePlanEndpoint()` */
  static readonly MealsGeneratePlanEndpointPath = '/meals-features/generate-plan';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `mealsGeneratePlanEndpoint()` instead.
   *
   * This method doesn't expect any request body.
   */
  mealsGeneratePlanEndpoint$Response(params?: MealsGeneratePlanEndpoint$Params, context?: HttpContext): Observable<StrictHttpResponse<MealsGeneratePlanResponse>> {
    return mealsGeneratePlanEndpoint(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `mealsGeneratePlanEndpoint$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  mealsGeneratePlanEndpoint(params?: MealsGeneratePlanEndpoint$Params, context?: HttpContext): Observable<MealsGeneratePlanResponse> {
    return this.mealsGeneratePlanEndpoint$Response(params, context).pipe(
      map((r: StrictHttpResponse<MealsGeneratePlanResponse>): MealsGeneratePlanResponse => r.body)
    );
  }

}
