CREATE TABLE MealPlan (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId TEXT NOT NULL, -- Storing GUID as TEXT because SQLite doesn't have a native GUID type
    CreatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MealDay (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    MealPlanId INTEGER NOT NULL,
    Day TEXT NOT NULL,
    FOREIGN KEY (MealPlanId) REFERENCES MealPlan(Id) ON DELETE CASCADE
);

CREATE TABLE Meal (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    MealDayId INTEGER NOT NULL,
    MealType TEXT NOT NULL,
    Food TEXT NOT NULL,
    FOREIGN KEY (MealDayId) REFERENCES MealDay(Id) ON DELETE CASCADE
);
