/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MealsRetrievePlansResponse } from '../../models/meals-retrieve-plans-response';

export interface MealsRetrievePlansEndpoint$Params {
}

export function mealsRetrievePlansEndpoint(http: HttpClient, rootUrl: string, params?: MealsRetrievePlansEndpoint$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MealsRetrievePlansResponse>>> {
  const rb = new RequestBuilder(rootUrl, mealsRetrievePlansEndpoint.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MealsRetrievePlansResponse>>;
    })
  );
}

mealsRetrievePlansEndpoint.PATH = '/meals-features/retrieve-plans';
