/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserUpdateUserDataRequest } from '../../models/user-update-user-data-request';
import { UserUpdateUserDataResponse } from '../../models/user-update-user-data-response';

export interface UserUpdateUserDataEndpoint$Params {
      body: UserUpdateUserDataRequest
}

export function userUpdateUserDataEndpoint(http: HttpClient, rootUrl: string, params: UserUpdateUserDataEndpoint$Params, context?: HttpContext): Observable<StrictHttpResponse<UserUpdateUserDataResponse>> {
  const rb = new RequestBuilder(rootUrl, userUpdateUserDataEndpoint.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserUpdateUserDataResponse>;
    })
  );
}

userUpdateUserDataEndpoint.PATH = '/user-features/update-user-data';
