/* tslint:disable */ /* eslint-disable */ /* Code generated by ng-openapi-gen DO NOT EDIT. */

export { type
  DotsMealsApiFeaturesTestRequest
  } from './models/dots-meals-api-features-test-request';
export { type
  DotsMealsApiFeaturesTestResponse
  } from './models/dots-meals-api-features-test-response';
export { type
  DotsMealsDalEnumsActivityLevels
  } from './models/dots-meals-dal-enums-activity-levels';
export { type
  DotsMealsDalEnumsDietType
  } from './models/dots-meals-dal-enums-diet-type';
export { type
  DotsMealsDalEnumsGenders
  } from './models/dots-meals-dal-enums-genders';
export { type
  EnumsRetrieveTranslationsEnumOption
  } from './models/enums-retrieve-translations-enum-option';
export { type
  EnumsRetrieveTranslationsEnumOptions
  } from './models/enums-retrieve-translations-enum-options';
export { type
  FastEndpointsErrorResponse
  } from './models/fast-endpoints-error-response';
export { type
  MealsGeneratePlanResponse
  } from './models/meals-generate-plan-response';
export { type
  MealsRetrievePlansResponse
  } from './models/meals-retrieve-plans-response';
export { type
  UserRetrieveLoggedUserResponse
  } from './models/user-retrieve-logged-user-response';
export { type
  UserUpdateUserDataRequest
  } from './models/user-update-user-data-request';
export { type
  UserUpdateUserDataResponse
  } from './models/user-update-user-data-response';
